# Source: Based on standard GitHub Action patterns
name: 'QWED Finance Guard'
description: 'Deterministically verify banking math (NPV, IRR) and prevent hallucinations in CI/CD.'
author: 'QWED-AI'
branding:
  icon: 'shield'  # Shows up as a Shield in Marketplace
  color: 'green'
inputs:
  file-path:
    description: 'Path to the CSV or JSON file containing financial data'
    required: true
    default: 'data/transactions.csv'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.file-path }}
